#!/usr/bin/env bash
# check-ports.sh — detect host port conflicts and write root .env overrides.
# Usage: scripts/check-ports.sh [--non-interactive]
# Exits 0 on success; exits 1 if a conflict cannot be resolved without a TTY.
set -euo pipefail

ROOT_ENV="$(cd "$(dirname "$0")/.." && pwd)/.env"
NON_INTERACTIVE=false
[[ "${1:-}" == "--non-interactive" ]] && NON_INTERACTIVE=true

port_in_use() {
  local port="$1"
  if command -v lsof &>/dev/null; then
    lsof -iTCP:"$port" -sTCP:LISTEN -P -n &>/dev/null
  else
    nc -z 127.0.0.1 "$port" &>/dev/null
  fi
}

prompt_port() {
  local service="$1" default="$2"
  if $NON_INTERACTIVE; then
    echo "ERROR: Port $default ($service) is in use. Set ${service}_PORT in root .env and re-run." >&2
    exit 1
  fi
  local alt
  while true; do
    printf "  Port %d (%s) is already in use. Enter an alternative [%d]: " "$default" "$service" "$((default + 1))" >&2
    read -r alt
    alt="${alt:-$((default + 1))}"
    if ! port_in_use "$alt"; then
      echo "$alt"
      return
    fi
    printf "  Port %d is also in use. Try another.\n" "$alt" >&2
  done
}

if [[ -f "$ROOT_ENV" ]]; then
  echo "Root .env already exists — skipping port check (delete it to re-run)."
  exit 0
fi

# ── Port conflict detection ───────────────────────────────────────────────────

KEYS=(DOC_REGISTRY_PORT AGENTS_PORT UI_PORT POSTGRES_PORT)
DEFAULTS=(8080 2024 3000 5432)

RESOLVED_KEYS=()
RESOLVED_VALUES=()
CONFLICT=false

for i in "${!KEYS[@]}"; do
  key="${KEYS[$i]}"
  default="${DEFAULTS[$i]}"
  if port_in_use "$default"; then
    CONFLICT=true
    service="${key//_PORT/}"
    chosen=$(prompt_port "$service" "$default")
    RESOLVED_KEYS+=("$key")
    RESOLVED_VALUES+=("$chosen")
  fi
done

if $CONFLICT; then
  printf "\nPort conflicts resolved:\n"
  for i in "${!RESOLVED_KEYS[@]}"; do
    printf "  %s=%s\n" "${RESOLVED_KEYS[$i]}" "${RESOLVED_VALUES[$i]}"
  done
else
  echo "No port conflicts — using defaults (8080, 2024, 3000, 5432)."
fi

# ── Write root .env ───────────────────────────────────────────────────────────

{
  echo "# Auto-generated by scripts/check-ports.sh — edit to change settings."
  echo "# Re-generate: delete this file and re-run 'make setup'."
  echo ""
  if [[ ${#RESOLVED_KEYS[@]} -gt 0 ]]; then
    echo "# ── Port overrides (auto-detected conflicts) ─────────────────────────────────"
    for i in "${!RESOLVED_KEYS[@]}"; do
      echo "${RESOLVED_KEYS[$i]}=${RESOLVED_VALUES[$i]}"
    done
    echo ""
  fi
} > "$ROOT_ENV"

printf "\nWrote %s:\n" "$ROOT_ENV" >&2
[[ ${#RESOLVED_KEYS[@]} -gt 0 ]] && for i in "${!RESOLVED_KEYS[@]}"; do
  printf "  %s=%s\n" "${RESOLVED_KEYS[$i]}" "${RESOLVED_VALUES[$i]}"
done
printf "\n"
