#!/usr/bin/env bash
# check-ports.sh — detect host port conflicts and select backend drivers; writes root .env.
# Usage: scripts/check-ports.sh [--non-interactive]
# Exits 0 on success; exits 1 if a conflict cannot be resolved without a TTY.
set -euo pipefail

ROOT_ENV="$(cd "$(dirname "$0")/.." && pwd)/.env"
NON_INTERACTIVE=false
[[ "${1:-}" == "--non-interactive" ]] && NON_INTERACTIVE=true

port_in_use() {
  local port="$1"
  if command -v lsof &>/dev/null; then
    lsof -iTCP:"$port" -sTCP:LISTEN -P -n &>/dev/null
  else
    nc -z 127.0.0.1 "$port" &>/dev/null
  fi
}

prompt_port() {
  local service="$1" default="$2"
  if $NON_INTERACTIVE; then
    echo "ERROR: Port $default ($service) is in use. Set ${service}_PORT in root .env and re-run." >&2
    exit 1
  fi
  local alt
  while true; do
    printf "  Port %d (%s) is already in use. Enter an alternative [%d]: " "$default" "$service" "$((default + 1))" >&2
    read -r alt
    alt="${alt:-$((default + 1))}"
    if ! port_in_use "$alt"; then
      echo "$alt"
      return
    fi
    printf "  Port %d is also in use. Try another.\n" "$alt" >&2
  done
}

pick_driver() {
  # pick_driver <label> <opt1_key> <opt1_desc> <opt2_key> <opt2_desc> [default_index]
  # Prints the chosen key to stdout.
  local label="$1" k1="$2" d1="$3" k2="$4" d2="$5" default_idx="${6:-1}"
  if $NON_INTERACTIVE; then
    if [[ "$default_idx" == "1" ]]; then echo "$k1"; else echo "$k2"; fi
    return
  fi
  printf "\n  %s:\n" "$label" >&2
  printf "    1) %-6s — %s%s\n" "$k1" "$d1" "$([ "$default_idx" == "1" ] && echo " (default)" || echo "")" >&2
  printf "    2) %-6s — %s%s\n" "$k2" "$d2" "$([ "$default_idx" == "2" ] && echo " (default)" || echo "")" >&2
  local choice
  while true; do
    printf "  Choice [%s]: " "$default_idx" >&2
    read -r choice
    choice="${choice:-$default_idx}"
    case "$choice" in
      1) echo "$k1"; return ;;
      2) echo "$k2"; return ;;
      *) printf "  Please enter 1 or 2.\n" >&2 ;;
    esac
  done
}

if [[ -f "$ROOT_ENV" ]]; then
  echo "Root .env already exists — skipping port check and driver selection (delete it to re-run)."
  exit 0
fi

# ── Port conflict detection ───────────────────────────────────────────────────

KEYS=(DOC_REGISTRY_PORT AGENTS_PORT UI_PORT POSTGRES_PORT)
DEFAULTS=(8080 2024 3000 5432)

RESOLVED_KEYS=()
RESOLVED_VALUES=()
CONFLICT=false

for i in "${!KEYS[@]}"; do
  key="${KEYS[$i]}"
  default="${DEFAULTS[$i]}"
  if port_in_use "$default"; then
    CONFLICT=true
    service="${key//_PORT/}"
    chosen=$(prompt_port "$service" "$default")
    RESOLVED_KEYS+=("$key")
    RESOLVED_VALUES+=("$chosen")
  fi
done

if $CONFLICT; then
  printf "\nPort conflicts resolved:\n"
  for i in "${!RESOLVED_KEYS[@]}"; do
    printf "  %s=%s\n" "${RESOLVED_KEYS[$i]}" "${RESOLVED_VALUES[$i]}"
  done
else
  echo "No port conflicts — using defaults (8080, 2024, 3000, 5432)."
fi

# ── Driver selection ──────────────────────────────────────────────────────────

if ! $NON_INTERACTIVE; then
  printf "\nBackend driver setup:\n" >&2
fi

QUEUE_DRIVER=$(pick_driver \
  "Queue driver" \
  "sync"  "inline processing, no Redis required" \
  "redis" "async via asynq, requires REDIS_URL" \
  1)

STORAGE_DRIVER=$(pick_driver \
  "Storage driver" \
  "local" "filesystem under BLOB_DATA_ROOT, no MinIO required" \
  "s3"    "MinIO / S3, requires S3_ENDPOINT + credentials" \
  1)

# ── Write root .env ───────────────────────────────────────────────────────────

{
  echo "# Auto-generated by scripts/check-ports.sh — edit to change settings."
  echo "# Re-generate: delete this file and re-run 'make setup'."
  echo ""
  if [[ ${#RESOLVED_KEYS[@]} -gt 0 ]]; then
    echo "# ── Port overrides (auto-detected conflicts) ─────────────────────────────────"
    for i in "${!RESOLVED_KEYS[@]}"; do
      echo "${RESOLVED_KEYS[$i]}=${RESOLVED_VALUES[$i]}"
    done
    echo ""
  fi
  echo "# ── Backend drivers ──────────────────────────────────────────────────────────"
  echo "QUEUE_DRIVER=${QUEUE_DRIVER}"
  echo "STORAGE_DRIVER=${STORAGE_DRIVER}"
} > "$ROOT_ENV"

printf "\nWrote %s:\n" "$ROOT_ENV" >&2
[[ ${#RESOLVED_KEYS[@]} -gt 0 ]] && for i in "${!RESOLVED_KEYS[@]}"; do
  printf "  %s=%s\n" "${RESOLVED_KEYS[$i]}" "${RESOLVED_VALUES[$i]}"
done
printf "  QUEUE_DRIVER=%s\n" "$QUEUE_DRIVER"
printf "  STORAGE_DRIVER=%s\n" "$STORAGE_DRIVER"
printf "\n"
