#!/usr/bin/env bash
# dev-secrets.sh — make `make run` work from a clean checkout without manual key
# setup. Idempotent: only fills in what is missing.
#
#   - SETTINGS_ENCRYPTION_KEY must exist BEFORE the server boots (it encrypts the
#     settings store), so it cannot live in the DB — this script generates it
#     into .env.
#   - mcp.api_key is auto-generated by the server into the settings DB on first
#     start (see internal/mcp/EnsureAPIKey), so it needs no env entry.
set -euo pipefail

cd "$(dirname "$0")/../app/doc-registry" # doc-registry module root

ENV_FILE=".env"
EXAMPLE=".env.example"

if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -f "$EXAMPLE" ]]; then
    cp "$EXAMPLE" "$ENV_FILE"
    echo "==> created $ENV_FILE from $EXAMPLE"
  else
    touch "$ENV_FILE"
  fi
fi

current="$(grep -E '^SETTINGS_ENCRYPTION_KEY=' "$ENV_FILE" | head -n1 | cut -d= -f2- || true)"
if [[ -n "${current//[[:space:]]/}" ]]; then
  echo "==> SETTINGS_ENCRYPTION_KEY already set; leaving it."
  exit 0
fi

# 32-byte hex key (prefer openssl; fall back to /dev/urandom).
if command -v openssl >/dev/null 2>&1; then
  key="$(openssl rand -hex 32)"
else
  key="$(head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi

if grep -qE '^SETTINGS_ENCRYPTION_KEY=' "$ENV_FILE"; then
  tmp="$(mktemp)"
  awk -v k="$key" '/^SETTINGS_ENCRYPTION_KEY=/{print "SETTINGS_ENCRYPTION_KEY=" k; next} {print}' "$ENV_FILE" >"$tmp"
  mv "$tmp" "$ENV_FILE"
else
  printf '\nSETTINGS_ENCRYPTION_KEY=%s\n' "$key" >>"$ENV_FILE"
fi

echo "==> generated SETTINGS_ENCRYPTION_KEY into $ENV_FILE"
echo "    (mcp.api_key auto-generates into the settings DB on first server start)"
